version: '3.8'

services:
  app:
    build: .
    command: 'npm run dev'
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-network-raizen

  mysql:
    build: ./.docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "33006:3306"
    networks:
      - app-network-raizen

networks:
  app-network-raizen:
    driver: bridge